// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmcO2pASH_A1Wypb7j6kMmTDvskZKMwn4',
    appId: '1:898649103715:web:4317e0abdcd0e3beb90756',
    messagingSenderId: '898649103715',
    projectId: 'somtalent-app',
    authDomain: 'somtalent-app.firebaseapp.com',
    storageBucket: 'somtalent-app.firebasestorage.app',
    measurementId: 'G-11X20PFQKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKh3Il9fsyFGoRFA5sQuvEsFvVWgIC0i0',
    appId: '1:898649103715:android:71e5e00d466c0bafb90756',
    messagingSenderId: '898649103715',
    projectId: 'somtalent-app',
    storageBucket: 'somtalent-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LoXBJHkvt_RPv-FxGIvWI9QJplyBqSg',
    appId: '1:898649103715:ios:76669e47abb291feb90756',
    messagingSenderId: '898649103715',
    projectId: 'somtalent-app',
    storageBucket: 'somtalent-app.firebasestorage.app',
    iosClientId:
        '898649103715-lfpti7rveo7rglpurlu61rfkcg9ilmlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6LoXBJHkvt_RPv-FxGIvWI9QJplyBqSg',
    appId: '1:898649103715:ios:76669e47abb291feb90756',
    messagingSenderId: '898649103715',
    projectId: 'somtalent-app',
    storageBucket: 'somtalent-app.firebasestorage.app',
    iosClientId:
        '898649103715-lfpti7rveo7rglpurlu61rfkcg9ilmlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmcO2pASH_A1Wypb7j6kMmTDvskZKMwn4',
    appId: '1:898649103715:web:3cbb0683969a5254b90756',
    messagingSenderId: '898649103715',
    projectId: 'somtalent-app',
    authDomain: 'somtalent-app.firebaseapp.com',
    storageBucket: 'somtalent-app.firebasestorage.app',
    measurementId: 'G-21WBTF4LET',
  );
}